name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v4.9.1
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 *.py
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast

  build_image:
    needs: [lint]
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: GCloud Auth
      id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Set up GCloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set run/region ${{ secrets.GCP_REGION }}
        gcloud auth configure-docker ${{ secrets.GCP_HOST_NAME }}
        gcloud info

    - name: Build and tag image
      run: docker build -t "${{ secrets.GCP_HOST_NAME }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_DOCKER_REPO_ID }}/${{ env.APPLICATION_NAME }}:latest" .

    - name: Push to GCP image registry
      run: docker push ${{ secrets.GCP_HOST_NAME }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_DOCKER_REPO_ID }}/${{ env.APPLICATION_NAME }}:latest

  test_image:
    needs: [build_image]
    runs-on: ubuntu-22.04
    steps:
    - name: GCloud Auth
      id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Set up GCloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set run/region ${{ secrets.GCP_REGION }}
        gcloud auth configure-docker ${{ secrets.GCP_HOST_NAME }}
        gcloud info

    - name: Run unit tests in container
      run: docker run "${{ secrets.GCP_HOST_NAME }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_DOCKER_REPO_ID }}/${{ env.APPLICATION_NAME }}:latest" -m unittest --verbose --failfast
